version: '3'

services:
  eureka:
    build: ./eureka-server
    ports:
      - '8761:8761'
    environment:
      - SPRING_PROFILES_ACTIVE=dockernet
  api-gateway:
    build: ./api-gateway
    ports:
      - '8080:8080'
    depends_on:
      - eureka
    environment:
      - SPRING_PROFILES_ACTIVE=dockernet
