zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: auth
      sensitiveHeaders:
    signup:
      path: /signup/**
      serviceId: auth
      strip-prefix: false
    login:
      path: /login/**
      serviceId: auth
      strip-prefix: false
    profile:
      path: /profile
      serviceId: profile
      sensitiveHeaders:
      strip-prefix: false
    post:
      path: /post
      serviceId: post
      sensitiveHeaders:
      strip-prefix: false
    listPosts:
      path: /post/list
      serviceId: post
      sensitiveHeaders:
      strip-prefix: false
    deletePostById:
      path: /post/*
      serviceId: post
      sensitiveHeaders:
      strip-prefix: false
    


jwt:
  secret: batarian
