zuul:
  routes:
    roles:
      path: /role/**
      serviceId: user
      strip-prefix: false
    signup:
      path: /signup/**
      serviceId: user
      strip-prefix: false
    login:
      path: /login/**
      serviceId: user
      strip-prefix: false
    profile:
      path: /profile
      serviceId: profile
      sensitiveHeaders:
      strip-prefix: false
    post:
      path: /post
      serviceId: post
      sensitiveHeaders:
      strip-prefix: false
    userPosts:
      path: /user/post
      serviceId: post
      sensitiveHeaders:
      strip-prefix: false
    listPosts:
      path: /post/list
      serviceId: post
      sensitiveHeaders:
      strip-prefix: false
    deletePostById:
      path: /post/*
      serviceId: post
      sensitiveHeaders:
      strip-prefix: false
    getCommentsByPostId:
      path: /post/*/comment
      serviceId: comment
      strip-prefix: false
    comment:
      path: /comment/**
      serviceId: comment
      sensitiveHeaders:
      strip-prefix: false
    commentsByUser:
      path: /user/comment
      serviceId: comment
      sensitiveHeaders:
      strip-prefix: false
  ignored-services: '*'

jwt:
  secret: batarian
