zuul:
  routes:
    signup:
      path: /signup/**
      serviceId: auth
      strip-prefix: false
    login:
      path: /login/**
      serviceId: auth
      strip-prefix: false
    post:
      path: /post
      serviceId: posts
      sensitiveHeaders:
      strip-prefix: false

