server:
  port: 9093


eureka:
  instance:
    appname: documentation
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

swagger:
  config:
    refreshrate: 5000

spring:
  application:
    name: documentation

logging:
  file: documentation-service.log
